package com.zxd.mybatis.mapper;


import com.zxd.mybatis.model.ResultDto;

import java.util.List;

public interface ResultDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table result
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String number);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table result
     *
     * @mbggenerated
     */
    int insert(ResultDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table result
     *
     * @mbggenerated
     */
    int insertSelective(ResultDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table result
     *
     * @mbggenerated
     */
    ResultDto selectByPrimaryKey(String number);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table result
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ResultDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table result
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ResultDto record);

    List<ResultDto> getAll();
}